name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test git-cliff
    if: |
      (
        github.actor != 'dependabot[bot]' &&
        github.actor != 'dependabot' &&
        github.actor != 'github-actions[bot]'
      )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: shellcheck
        uses: reviewdog/action-shellcheck@v1
